# Generated by Django 4.1 on 2022-08-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form34b', '0003_alter_formdetails_voter_turnout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdetails',
            name='voter_turnout',
            field=models.IntegerField(default=0),
        ),
    ]
