# Generated by Django 4.1 on 2022-08-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form34b', '0006_candidate_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdetails',
            name='mweure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formdetails',
            name='odinga',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formdetails',
            name='ruto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formdetails',
            name='wajackoyah',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
